namespace: ${namespace}
serviceAccountName: ${service_account_name}
image: ${acr_url}/${mlproject_image_name}

# Command to execute (mlflow run <path> -e <entrypoint-name> --param1 value1)
command: "mlflow run mlflow_project -e train"

# Path inside mounted storage
# projectPath: /mnt/mlprojects/projectA

# # Which entrypoint to run
# entryPoint: train

# # MLflow experiment
# experimentName: lasso_experiment

# MLflow server
mlflowTrackingUri: http://${tracking_server_service_name}.${namespace}.svc:5000

# PVC name that mounts Azure Storage
pvcName: azurefiles-pvc