# When running a MLflow project in a Job deployed using the mlflow_project chart, MLproject files will be provided from Azure Storage Account
# through a mounting. It works in this way:
# - Mount a Volume to the Job running MLflow project
# - Volume uses a Azure file Storage Class to store data in a File share in Azure Storage Account
# - Storage Class uses a secret to access Storage Account
# This is the secret used by the Storage Class from this process.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mlflowProjectMounting.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.mlflowProjectMounting.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.mlflowProjectMounting.storageAccountKey | b64enc }}