# This Service Account will be used when we run a MLflow project using the mlflow_project chart for authentication when reading a secret used to pull an image from ACR.
# We will assign to is a proper role in the service-account-role-binding.yaml template.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mlflow.serviceAccountName }}
  namespace: {{ .Values.namespace }}
imagePullSecrets:
- name: {{ .Values.acrSecret.secretName }}