# Deployment for running MLflow Tracking Server.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      # Get a secret with value for authentication to the ACR.
      imagePullSecrets:
        - name: {{ .Values.acrSecret.secretName }}
      containers:
      - name: mlflow
        image: "{{ .Values.acr.url }}/{{ .Values.acr.trackingServerImageName }}"
        ports:
        - containerPort: 5000
        env:
        # Create environment variables with values from the secret created as well in this chart. They will be used by the
        # MLflow Tracking Server for authentication when connecting to the artifact store (Storage Account) and backend store (MySQL).
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mlflow.trackingServerSecretName }}
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mlflow.trackingServerSecretName }}
              key: DB_URI
        # Run the command to start the Tracking Server
        command: ["mlflow"]
        args:
          [
            "server",
            "--host", "0.0.0.0",
            "--port", "5000",
            "--backend-store-uri", "$(DB_URI)",
            "--artifacts-destination", "wasbs://{{ .Values.mlflow.mlflowContainerName }}@{{ .Values.mlflow.mlflowStorageAccountName }}.blob.core.windows.net/"
          ]