# Create a secret with values for accessing the Azure Blob Storage and MySQL.
# This secret will be used when deploying MLflow Tracking Server.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mlflow.trackingServerSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.mlflow.azureConnectionString }}
  DB_URI: "mysql://{{ .Values.mysql.auth.username }}:{{ .Values.mysql.auth.password }}@{{ .Values.mysql.fullnameOverride  }}.{{ .Values.namespace }}.svc.cluster.local:3306/{{ .Values.mysql.auth.database }}"